// AuraMain.swift
// `@main` entry for the Aura iOS app target generated by xcodegen. Library
// targets cannot declare `@main`, so the SPM build excludes this file (see
// `Package.swift` `exclude:`). The Xcode app target picks it up to wire
// `AuraApp` (defined in `AuraApp.swift`) as the process entrypoint.
//
// Background-task registration runs as early as possible so the system can
// dispatch the BGAppRefreshTask / BGProcessingTask the agents depend on.
import SwiftUI
#if canImport(BackgroundTasks)
import BackgroundTasks
#endif

@available(iOS 17.0, *)
@main
struct AuraAppMain: App {
	@StateObject private var silenceBudget = SilenceBudget()
	@StateObject private var bridge = AuraBridge.shared
	@UIApplicationDelegateAdaptor(AuraAppDelegate.self) private var appDelegate

	var body: some Scene {
		WindowGroup {
			RootTabView()
				.environmentObject(silenceBudget)
				.environmentObject(bridge)
				.tint(Color("AccentColor"))
				.task {
					_ = await bridge.ping()
					await silenceBudget.scheduleMidnightReset()
					SilenceBudget.scheduleNextBackgroundWork()
					try? await MemoryService.shared.open()
				}
		}
	}
}

#if canImport(UIKit)
import UIKit

/// AppDelegate exists only to register background tasks at the earliest
/// point in the launch lifecycle. iOS requires `BGTaskScheduler.register(...)`
/// to run before the app finishes launching.
final class AuraAppDelegate: NSObject, UIApplicationDelegate {
	func application(
		_ application: UIApplication,
		didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil
	) -> Bool {
		SilenceBudget.registerBackgroundTasks(
			refresh: { Self.handleRefresh() },
			process: { Self.handleProcessing() }
		)
		return true
	}

	private static func handleRefresh() {
		// The orchestrator polls health + calendar from the FastAPI bridge.
		// Schedule the next refresh so the loop continues.
		SilenceBudget.scheduleNextBackgroundWork()
	}

	private static func handleProcessing() {
		// Nightly memory chores: vacuum, recompute Merkle root.
		SilenceBudget.scheduleNextBackgroundWork()
	}
}
#endif
